name: engine_method_noerror.bas File Generator
on: [push]
jobs:
    create-engine-no-error-file:
        runs-on: ubuntu-latest
        steps:
        - name: Run python script
          run: 
            echo "running script"
            python auto-generate.py
            git config --local user.email 'ashishkushwahacb@gmail.com'
            git config --local user.name 'auto-generate'
            git add engine_method_noerror.bas
            if [[ $(git diff --cached | wc -l) -gt 0 ]]; git commit -m "update engine_method_noerror.bas"; fi
            git push --all
